name = "course-tracker"
type = "javascript"

account_id = "e87c4fc19e7e2d0becae173112809d75"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = " appsCfhuuWmDBO7Pp"
AIRTABLE_TABLE_NAME = "Course tracker"
FORM_URL = "https://workers-airtable-form.pages.dev"